Anchor 0.30 upgrade
jito-foundation/jito-programs pull request #117
Opened 2024-05-01 16:12 UTC by ebatsell

2024-06-03 02:12 UTC, Meeklowg requested changes
No weapon formed against me shall prosper! I AM Law Above The Law enforcement

2024-10-02 06:36 UTC, mooncityorg reviewed
jito bundling is possible?

2024-11-04 06:58 UTC, MrG9090 approved these changes

2024-11-04 06:59 UTC, MrG9090 approved these changes

2024-11-22 19:47 UTC, MrG9090 approved these changes

2024-11-22 19:57 UTC, MrG9090 approved these changes

2024-11-22 19:58 UTC, MrG9090 approved these changes

2024-11-22 20:17 UTC, MrG9090 approved these changes

2024-12-08 02:51 UTC, MrG9090 approved these changes

2024-12-10 18:51 UTC, MrG9090 approved these changes

2025-01-09 19:44 UTC, closed without merging

2025-01-10 07:07 UTC, MrG9090 approved these changes